//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int articleID { get; set; }
        public string title { get; set; }
        public string highlightText { get; set; }
        public string imgUrl { get; set; }
        public string articleContent { get; set; }
        public System.DateTime uploadDateTime { get; set; }
        public Nullable<System.DateTime> lastUpdateDateTime { get; set; }
        public string writer { get; set; }
        public byte isDelete { get; set; }
    }
}
