LOG_LEVEL_VERBOSE = 0
LOG_LEVEL_INFO = 1
LOG_LEVEL_DEBUG = 2
LOG_LEVEL_WARN = 3
LOG_LEVEL_ERROR = 4

LOG_LEVEL_VERBOSE_STR = "V"
LOG_LEVEL_INFO_STR = "I"
LOG_LEVEL_DEBUG_STR = "D"
LOG_LEVEL_WARN_STR = "W"
LOG_LEVEL_ERROR_STR = "E"

HIDE_ELEMENTS = 0
SHOW_ELEMENTS = 1

ENDPOINT_APPEND_NEW_USER = "/Blog/NewUser"

API_GET_CURRENT_PAGE_LATEST_ARTICLE = "/api/BlogApi/GetCurrentPageArticleInfo/"
API_GET_SHOW_SELECTED_ARTICLE = "/api/BlogApi/ShowSelectedArticle/"